#!/bin/bash
SERVICE=`./getServiceName`
CONTAINER=`./getServiceName 4`
ORG=`./getServiceName 1`
echo "---------------------------------------------------------------------------------------"
echo "Compiling $ORG/$SERVICE Microservice"
echo "---------------------------------------------------------------------------------------"
echo "Changing Logback Log File Name: /tmp/$SERVICE-server.%d{yyyy-MM-dd}.%i.log"
echo "---------------------------------------------------------------------------------------"
sed -i -r "s/microservice/$SERVICE/g" src/main/resources/logback.xml
sed -i -r "s/microservice/$SERVICE/g" src/main/resources/logback-test.xml
echo "Clean up the target folder: mvn clean"
echo "---------------------------------------------------------------------------------------"
mvn clean
echo "Git Commit Count = "`git rev-list HEAD --count`
echo "---------------------------------------------------------------------------------------"
./generateBuildNumber $SERVICE
echo "Build the $ORG/$SERVICE Microservice : mvn -e package"
echo "---------------------------------------------------------------------------------------"
mvn -e package
mvnCompRV=$?
if [ $mvnCompRV -eq 0 ]; then
	echo "---------------------------------------------------------------------------------------"
	echo "Compiling Service > $ORG/$SERVICE :: SUCCESS"
	echo "---------------------------------------------------------------------------------------"
	echo "Copy the Fat and Thin jar files and the libs to the Docker Directory (src/docker)"
	cp target/*service*-spring-boot.jar src/docker/$CONTAINER-spring-boot.jar
	#cp target/*service*.jar src/docker/$CONTAINER-thin.jar
	echo "Copy the application.properties File to the Docker Directory (src/docker)"
	cp src/main/resources/application*.properties src/docker/
	cd src/docker
	echo "---------------------------------------------------------------------------------------"
	echo "Building the Container for $ORG/$SERVICE Service ..... "
	echo "---------------------------------------------------------------------------------------"
	docker build -t $CONTAINER .
	echo "---------------------------------------------------------------------------------------"
	echo "$SERVICE Microservice Build Process Completed Successfully! ........... "
	echo "---------------------------------------------------------------------------------------"
	echo "Start the Service using "
	echo "  run (Run the SpringBoot App)  OR"
	echo "  cd src/docker"
	echo "  start (Start the Container)"
	echo "Then to test it with"
	echo "  test (To Test the SpringBoot App)"
	echo "---------------------------------------------------------------------------------------"
	echo "After the Successful build and Startup of the Service, It should show the Build No. & Date"
	echo "---------------------------------------------------------------------------------------"
else
	echo "---------------------------------------------------------------------------------------"
	echo "Compiling Service > $ORG/$SERVICE :: FAILED!!!"
	echo "---------------------------------------------------------------------------------------"
fi
