#!/bin/bash
# -------------------------------------------------------------------------------------------
# @author: Araf Karsh Hamid
# -------------------------------------------------------------------------------------------
SERVICE_NAME=$(./getServiceName 2)  # Gọi script và lấy giá trị của service name
echo "Starting $SERVICE_NAME Microservice"

#echo "Starting `getServiceName` Microservice"
export JDK_JAVA_OPTIONS="--add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED"
runMode=$1
# Check if the runMode is null or not one of "dev", "prod", or "staging"
if [[ -z $runMode || ($runMode != "dev" && $runMode != "prod" && $runMode != "staging") ]]
then
  runMode="dev"
fi
echo "App running with profile = $runMode"

# Run Maven Command
# mvn spring-boot:run -Dspring-boot.run.profiles=$runMode

# Run Java command
echo "java -jar target/ms-cache-service-*-spring-boot.jar --spring.profiles.active=$runMode"
java -jar target/ms-cache-service-*-spring-boot.jar --spring.profiles.active=$runMode
